language: python
python:
  - "3.6"

stages:
  - round_1
  - round_2
  - round_3
  - round_4
  - round_5
  - round_6
  - round_7
  - round_8
  - round_9
  - round_10
  - round_11
  - final_round_and_deploy

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: round_1
      script: python3 round_1.py
      cache: pip
    - stage: round_2
      script: python3 round_2.py
      cache: pip
    - stage: round_3
      script: python3 round_2.py
      cache: pip
    - stage: round_4
      script: python3 round_2.py
      cache: pip
    - stage: round_5
      script: python3 round_2.py
      cache: pip
    - stage: round_6
      script: python3 round_2.py
      cache: pip
    - stage: round_7
      script: python3 round_2.py
      cache: pip
    - stage: round_8
      script: python3 round_2.py
      cache: pip
    - stage: round_9
      script: python3 round_2.py
      cache: pip
    - stage: round_10
      script: python3 round_2.py
      cache: pip
    - stage: round_11
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "final_round_and_deploy"
      script: python3 stochastic_search.py
      cache: pip
      before_deploy:
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d_%H-%M')}
      - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.csv
        skip_cleanup: true
        on:
          tags: false





