language: python
python:
  - "3.6"

stages:
  - round_1
  - round_2
  - round_3
  - round_4
  - round_5
  - round_6
  - round_7
  - round_8
  - round_9
  - round_10
  - round_11
  - round_12
  - round_13
  - round_14
  - round_15
  - round_16
  - final_round_and_deploy

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: round_1
      script: g++ -pthread -lpthread -O3 -std=c++17 -o round_1 round_1.cpp && ./round_1
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_2
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_3
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_4
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_5
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_6
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_7
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_8
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_9
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_10
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_11
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_12
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_13
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_14
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_15
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: round_16
      script: python3 round_2.py
      cache: pip
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: temp
    - stage: final_round_and_deploy
      script: python3 stochastic_search.py
      cache: pip
      before_deploy:
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d_%H-%M')}
      - git tag $TRAVIS_TAG
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_KEY
        bucket: "comp2019opt"
        skip_cleanup: true
        local_dir: build





