language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: python3 stochastic_search.py

deploy:
  provider: releases
  api_key: "b36f79a6c44768f4aa333be4b4d152ccc6c17480"
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: false