language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage:
      name: "round_1"
      script: python3 round_1.py
      cache: pip
    - stage:
      name: "round_2"
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "round_3"
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "round_4"
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "round_5"
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "round_6"
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "round_7"
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "round_8"
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "round_9"
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "round_10"
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "round_11"
      script: python3 round_2.py
      cache: pip
    - stage:
      name: "final_round_and_deploy"
      script: python3 stochastic_search.py
      cache: pip
      before_deploy:
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d_%H-%M')}
      - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.csv
        skip_cleanup: true
        on:
          tags: false





