language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: python3 stochastic_search.py

before_deploy:
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
      - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: build/*.csv
  skip_cleanup: true
  on:
    tags: false