language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: round 1
      script: python3 round_1.py
      skip_cleanup: true
    - stage: round 2
      script: python3 round_2.py
      skip_cleanup: true
    - stage: round 3
      script: python3 stochastic_search.py
    - stage: deploy
      before_deploy:
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d_%H-%M')}
      - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.csv
        skip_cleanup: true
        on:
          tags: false





