language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: round 1
      script: python3 round_1.py
      cache: pip
    - stage: round 2
      script: python3 round_2.py
      cache: pip
    - stage: round 3
      script: python3 round_2.py
      cache: pip
    - stage: round 4
      script: python3 round_2.py
      cache: pip
    - stage: round 5
      script: python3 round_2.py
      cache: pip
    - stage: round 6
      script: python3 round_2.py
      cache: pip
    - stage: round 7
      script: python3 round_2.py
      cache: pip
    - stage: round 8
      script: python3 round_2.py
      cache: pip
    - stage: round 9
      script: python3 round_2.py
      cache: pip
    - stage: round 10
      script: python3 round_2.py
      cache: pip
    - stage: round 11
      script: python3 round_2.py
      cache: pip
    - stage: final round and deploy
      script: python3 stochastic_search.py
      cache: pip
      before_deploy:
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y-%m-%d_%H-%M')}
      - git tag $TRAVIS_TAG
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: build/*.csv
        skip_cleanup: true
        on:
          tags: false





