language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script: python3 stochastic_search.py

deploy:
  provider: releases
  api_key: "GITHUB_TOKEN"
  file_glob: true
  file: build/*
  skip_cleanup: true
  on:
    tags: false